baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Teresa's Blog"
theme = "anatole"
enableEmoji = true
paginate = 10

[params]
title = "Teresa Jie"
author = "Teresa Jie"
description = "Welcome to my cozy cafe blog ☕"
profilePicture = "images/profile.jpg"
favicon = "images/favicon.ico"
mainSections = []
displayMode = "dark"

[params.social]
github = "teresajie"
email = "you@example.com"
